= SIPper
:toc: macro

A SIP (Session Initiation Protocol for soft phones) library for Java 21+ which doesn't suck (pun intended).

image:https://github.com/bmarwell/sipper/actions/workflows/maven-build.yml/badge.svg[Maven CI,link=https://github.com/bmarwell/sipper/actions/workflows/maven-build.yml]
image:https://img.shields.io/badge/License-Apache_2.0-blue.svg[License,link=https://opensource.org/licenses/Apache-2.0]
image:https://codecov.io/gh/bmarwell/sipper/graph/badge.svg?token=W70UTK1O1V[codecov.io,link=https://codecov.io/gh/bmarwell/sipper]
image:https://img.shields.io/badge/renovate-enabled-brightgreen.svg[Renovate,link=https://renovatebot.com]

toc::[]

== Development status

There is a basic set of interfaces in the API.
Using the API and a configuration, it is possible to connect (REGISTER) and disconnect (UNREGISTER aka REGISTER with Expires: 0).
Incoming calls are being detected, but not yet routed to the SipEventHandler class.

There is basically no test yet, except a few which are being used for development.

== API stability

None yet, goal is to have good stability before 0.4.0.

== Implementation details

This library will make use of the Java 6+ Service Loader mechanisms.
As a developer, you can code against the API only and have only the API in your class path whilst compiling.
But for the runtime, the implementation will be needed as well.
