name: Code style

on:
  workflow_dispatch: { }
  push: { }
  pull_request: { }


permissions:
  contents: read

jobs:
  codestyle:
    if: github.ref_name == 'main' || github.event_name != 'push' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    runs-on: [ 'ubuntu-latest' ]
    steps:

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: liberica

      - name: fetch main branch for spotless
        shell: bash
        run: git fetch origin main

      - name: Check whether you actually executed Maven...
        shell: bash
        run: >
          ./mvnw
          --show-version
          --errors
          --batch-mode
          --no-transfer-progress
          spotless:check
          -DtrimStackTrace=false 
