name: Maven CI

on:
  workflow_dispatch: { }
  push: { }
  pull_request: { }


permissions:
  contents: read

jobs:
  build:
    if: github.ref_name == 'main' || github.event_name != 'push' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    runs-on: [ 'ubuntu-latest' ]
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Cache local Maven Build Cache
        uses: actions/cache@v4.2.3
        if: ${{ github.ref_name != 'main' }}
        with:
          path: ~/.m2/build-cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: liberica

      - name: Build application with Maven
        shell: bash
        run: >
          ./mvnw
          --show-version
          --errors
          --batch-mode
          --no-transfer-progress
          verify
          -DtrimStackTrace=false
          -Dspotless.skip=true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
